SELECT 
   A.USERNAME
   , A.SID
   , A.SERIAL#
   , B.XIDUSN
   , B.PROCESS
   , B.LOCKED_MODE
   , C.OBJECT_NAME
   , A.SQL_ID
FROM 
   V$SESSION A
   , V$LOCKED_OBJECT B
   , DBA_OBJECTS C
WHERE 
   A.SID = B.SESSION_ID
   AND B.OBJECT_ID = C.OBJECT_ID
ORDER BY B.XIDUSN DESC;

ALTER SYSTEM KILL SESSION '96,10139';
busy¶ã¶§ ALTER SYSTEM KILL SESSION 'SID,'SERIAL' 
